"""Lark provider implementation owned by the extension layer."""

LARK_EXTENSION_ID = "loopx-lark"
LARK_INBOX_READ_PERMISSION = "lark.inbox.read"
LARK_INBOX_WRITE_PERMISSION = "lark.inbox.write"
LARK_REPLY_PERMISSION = "lark.reply.send"
LARK_COLLECTOR_PERMISSION = "lark.collector.manage"
LARK_REVIEWER_NOTIFICATION_PERMISSION = "lark.reviewer_notification.send"
LARK_PROJECTION_SINK_PERMISSION = "lark.projection_sink.use"
LARK_MIAODA_HTML_PERMISSION = "lark.miaoda_html.publish"
LARK_MEETING_PREP_PERMISSION = "lark.meeting_prep.read"
